# Generated by Django 2.0.9 on 2020-01-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=64, unique=True)),
                ('nickname', models.CharField(max_length=256)),
            ],
        ),
    ]
